DROP TABLESPACE IF EXISTS reclaim_ts INCLUDING CONTENTS AND DATAFILES;
CREATE SMALLFILE TABLESPACE reclaim_ts
DATAFILE
'/opt/oracle/oradata/FREE/FREEPDB1/reclaim_ts01.dbf' SIZE 10M AUTOEXTEND ON NEXT 1M,
'/opt/oracle/oradata/FREE/FREEPDB1/reclaim_ts02.dbf' SIZE 10M AUTOEXTEND ON NEXT 1M,
'/opt/oracle/oradata/FREE/FREEPDB1/reclaim_ts03.dbf' SIZE 10M AUTOEXTEND ON NEXT 1M,
'/opt/oracle/oradata/FREE/FREEPDB1/reclaim_ts04.dbf' SIZE 10M AUTOEXTEND ON NEXT 1M;

DROP USER if exists reclaim_user CASCADE;
CREATE USER reclaim_user
IDENTIFIED BY oracle
DEFAULT TABLESPACE reclaim_ts
QUOTA UNLIMITED ON reclaim_ts;
GRANT CREATE SESSION, CREATE TABLE TO reclaim_user;
GRANT SELECT_CATALOG_ROLE TO reclaim_user;

Shrinking Tablespaces P a g e | 3

CREATE TABLE t1 (
id NUMBER,
col1 VARCHAR2(4000),
col2 VARCHAR2(4000),
CONSTRAINT t1_pk PRIMARY KEY (id)
);
CREATE TABLE t2 (
id NUMBER,
col1 VARCHAR2(4000),
col2 VARCHAR2(4000),
CONSTRAINT t2_pk PRIMARY KEY (id)
);
-- Populate tables
INSERT INTO t1
SELECT rownum, RPAD('X', 4000, 'X'), RPAD('X', 4000, 'X')
FROM dual
CONNECT BY level <= 100000;
COMMIT;
INSERT INTO t2
SELECT rownum, RPAD('X', 4000, 'X'), RPAD('X', 4000, 'X')
FROM dual
CONNECT BY level <= 100000;
COMMIT;
exec DBMS_STATS.GATHER_TABLE_STATS(NULL, 't1');
exec DBMS_STATS.GATHER_TABLE_STATS(NULL, 't2');
